version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: comisiones-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comisiones_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - comisiones-network

  # Phpmyadmin opcional para administración visual
  phpmyadmin:
    image: phpmyadmin
    container_name: comisiones-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - comisiones-network

volumes:
  mysql_data:

networks:
  comisiones-network:
    driver: bridge
